#!/usr/bin/env node
// Apply review-pass decisions: read all 5 reviewer JSON files from
// /tmp/grammar_review/, intersect approvals against the on-disk 283 stories,
// drop rejections, regenerate src/app/grammar/lib/stories-generated.ts,
// and print a grammar-gap synthesis report.

const fs = require("fs");
const path = require("path");

const STORIES_DIR = "/tmp/grammar_stories";
const REVIEW_DIR = "/tmp/grammar_review";
const OUT_PATH =
  "/home/emoore/ciris-website/src/app/grammar/lib/stories-generated.ts";
const GAP_REPORT_PATH = "/tmp/grammar_review/GRAMMAR_GAPS.md";

const VALID_FAMILIES = new Set([
  "STANDING",
  "ACTION",
  "DETECTION",
  "CONSENSUS",
  "CORRECTION",
]);

function loadStories() {
  const out = [];
  const files = fs
    .readdirSync(STORIES_DIR)
    .filter((f) => /^agent_\d+\.json$/.test(f))
    .sort();
  for (const f of files) {
    const data = JSON.parse(
      fs.readFileSync(path.join(STORIES_DIR, f), "utf-8"),
    );
    for (const s of data) {
      s._sourceAgent = f.replace(/\.json$/, "");
      out.push(s);
    }
  }
  return out;
}

function loadReviews() {
  const out = [];
  const files = fs
    .readdirSync(REVIEW_DIR)
    .filter((f) => /^reviewer_[A-E]\.json$/.test(f))
    .sort();
  for (const f of files) {
    try {
      const data = JSON.parse(
        fs.readFileSync(path.join(REVIEW_DIR, f), "utf-8"),
      );
      out.push({ name: f.replace(/\.json$/, ""), ...data });
    } catch (e) {
      console.error(`Failed to parse ${f}: ${e.message}`);
    }
  }
  return out;
}

function extractDimensions(yaml) {
  const out = [];
  const re = /dimension:\s*["']?([^"'\r\n]+?)["']?\s*$/gm;
  let m;
  while ((m = re.exec(yaml)) !== null) out.push(m[1].trim());
  return out;
}

function prefixFamily(dim) {
  const parts = dim.split(":");
  return parts.length >= 2 ? parts.slice(0, 2).join(":") : parts[0];
}

function topLevelNamespace(dim) {
  return dim.split(":")[0];
}

function main() {
  const stories = loadStories();
  const reviews = loadReviews();
  console.log(`Loaded ${stories.length} stories`);
  console.log(`Loaded ${reviews.length} reviewer files`);

  if (reviews.length === 0) {
    console.error("No reviewer files found. Aborting.");
    process.exit(1);
  }

  // Aggregate approvals + rejections
  const approvedIds = new Set();
  const rejectedById = new Map();
  for (const r of reviews) {
    (r.approved ?? []).forEach((id) => approvedIds.add(id));
    (r.rejected ?? []).forEach((row) =>
      rejectedById.set(row.id, { reason: row.reason, reviewer: r.name }),
    );
  }

  // Final pass: keep stories that (a) are approved AND (b) not rejected
  // (in case a reviewer split a story across both lists).
  const kept = [];
  const dropped = [];
  for (const s of stories) {
    if (rejectedById.has(s.id)) {
      dropped.push({ id: s.id, ...rejectedById.get(s.id) });
      continue;
    }
    if (!approvedIds.has(s.id)) {
      // Story wasn't reviewed by anyone — pass through (review didn't reach it)
      kept.push(s);
      continue;
    }
    kept.push(s);
  }

  console.log(`Kept: ${kept.length}`);
  console.log(`Dropped: ${dropped.length}`);
  if (dropped.length > 0) {
    console.log("\nDropped stories:");
    dropped.forEach((d) =>
      console.log(`  [${d.reviewer}] ${d.id} — ${d.reason}`),
    );
  }

  // Family breakdown
  const byFamily = {};
  for (const s of kept) byFamily[s.family] = (byFamily[s.family] || 0) + 1;
  console.log("\nBy family:");
  Object.entries(byFamily).forEach(([k, v]) => console.log(`  ${k}: ${v}`));

  // Coverage: at top-level namespace (e.g., beneficence, detection, news)
  const nsCoverage = {};
  for (const s of kept) {
    const dims = extractDimensions(s.exampleYaml);
    const namespaces = new Set(dims.map(topLevelNamespace));
    for (const ns of namespaces) {
      nsCoverage[ns] = (nsCoverage[ns] || 0) + 1;
    }
  }
  console.log("\nTop-level namespace coverage:");
  Object.entries(nsCoverage)
    .sort((a, b) => b[1] - a[1])
    .forEach(([k, v]) => console.log(`  ${v}× ${k}`));

  // Emit the TypeScript module
  const banner = `// AUTO-GENERATED by scripts/apply_review.js — do not edit by hand.
// ${kept.length} stories surviving the 5-agent review pass on ${new Date().toISOString().slice(0, 10)}.
// Theme: "a kinder future" — sci-fi children's grammar primer for adults,
// appropriate for kids. Originally 283 stories from 9 generation agents;
// ${dropped.length} dropped during review.

import type { GeneratedStory } from "./shared";

`;

  const lines = ["export const ALL_STORIES: GeneratedStory[] = ["];
  for (const s of kept) {
    const dims = extractDimensions(s.exampleYaml);
    const families = [...new Set(dims.map(prefixFamily))];
    const obj = {
      id: s.id,
      title: s.title,
      scenario: s.scenario,
      primitives: families.length > 0 ? families : s.primitives,
      family: VALID_FAMILIES.has(s.family) ? s.family : "STANDING",
      walkthrough: s.walkthrough,
      exampleYaml: s.exampleYaml,
      dimensions: dims,
      sourceAgent: s._sourceAgent,
    };
    lines.push("  " + JSON.stringify(obj) + ",");
  }
  lines.push("];");
  lines.push("");
  lines.push(`export const STORY_COUNT = ${kept.length};`);
  lines.push(
    `export const STORY_FAMILIES = ${JSON.stringify(byFamily, null, 2)} as const;`,
  );

  fs.writeFileSync(OUT_PATH, banner + lines.join("\n") + "\n");
  console.log(`\nWrote ${OUT_PATH}`);

  // Build grammar-gap report
  const gapReport = [
    "# Grammar Gaps and Patterns — Review Synthesis",
    "",
    `Source: 5 review agents over ${stories.length} stories.`,
    `Result: ${kept.length} kept · ${dropped.length} dropped.`,
    "",
  ];

  if (dropped.length > 0) {
    gapReport.push("## Dropped stories");
    gapReport.push("");
    dropped.forEach((d) =>
      gapReport.push(`- **${d.id}** (${d.reviewer}) — ${d.reason}`),
    );
    gapReport.push("");
  }

  // Aggregate grammar_gaps across reviewers
  const allGaps = [];
  reviews.forEach((r) => {
    (r.grammar_gaps ?? []).forEach((g) =>
      allGaps.push({ ...g, reviewer: r.name }),
    );
  });
  if (allGaps.length > 0) {
    // Group by severity
    const bySeverity = { high: [], medium: [], low: [] };
    for (const g of allGaps) {
      const sev = (g.severity ?? "medium").toLowerCase();
      (bySeverity[sev] ?? bySeverity.medium).push(g);
    }
    gapReport.push("## Grammar gaps surfaced");
    gapReport.push("");
    for (const sev of ["high", "medium", "low"]) {
      const items = bySeverity[sev];
      if (items.length === 0) continue;
      gapReport.push(`### ${sev.toUpperCase()} severity`);
      gapReport.push("");
      items.forEach((g) => {
        gapReport.push(`**[${g.reviewer}] ${g.observation}**`);
        if (g.evidence_story_ids && g.evidence_story_ids.length > 0) {
          gapReport.push(`- Evidence: ${g.evidence_story_ids.join(", ")}`);
        }
        if (g.suggestion) {
          gapReport.push(`- Suggestion: ${g.suggestion}`);
        }
        gapReport.push("");
      });
    }
  }

  // Aggregate overlaps
  const allOverlaps = [];
  reviews.forEach((r) => {
    (r.overlaps ?? []).forEach((o) =>
      allOverlaps.push({ ...o, reviewer: r.name }),
    );
  });
  if (allOverlaps.length > 0) {
    gapReport.push("## Overlaps noted");
    gapReport.push("");
    allOverlaps.forEach((o) => {
      gapReport.push(`**[${o.reviewer}] ${o.description}**`);
      if (o.story_ids && o.story_ids.length > 0) {
        gapReport.push(`- Stories: ${o.story_ids.join(", ")}`);
      }
      if (o.recommendation) {
        gapReport.push(`- Recommendation: ${o.recommendation}`);
      }
      gapReport.push("");
    });
  }

  // Tone notes
  gapReport.push("## Tone notes (per reviewer)");
  gapReport.push("");
  reviews.forEach((r) => {
    if (r.tone_notes) {
      gapReport.push(`- **${r.name}**: ${r.tone_notes}`);
    }
  });
  gapReport.push("");

  // Extension health (from reviewer E if present)
  const extReviewer = reviews.find((r) => r.extension_health_notes);
  if (extReviewer) {
    gapReport.push("## News/Encyclopedia extension health (Reviewer E)");
    gapReport.push("");
    gapReport.push(extReviewer.extension_health_notes);
    gapReport.push("");
  }

  fs.writeFileSync(GAP_REPORT_PATH, gapReport.join("\n"));
  console.log(`Wrote ${GAP_REPORT_PATH}`);
}

main();
